export { default as GameLogo } from './game-logo.png';
export { default as MuteSoundIcon } from './icons/mute-icon.png';
export { default as SpeakerIcon } from './icons/speaker-icon.png';
export { default as SnooFacePNG } from './snoo-face.png';
export { default as LeaderboardSnoo } from './leaderboard-snoo.png';
export { default as HomeIcon } from './icons/home-icon.png';
export { default as BackArrowIcon } from './icons/backarrow-icon.png';
export { default as SnooRules } from './snoo-rules.png';
export { default as SnooExperimenting } from './snoo-experimenting.png';
export { default as Snoo4x4 } from './snoo-4x4.png';
export { default as Snoo5x5 } from './snoo-5x5.png';
export { default as Snoo6x6 } from './snoo-6x6.png';
export { default as Snoo7x7 } from './snoo-7x7.png';
export { default as Snoo8x8 } from './snoo-8x8.png';
export { default as Snoo9x9 } from './snoo-9x9.png';
export { default as Crown1 } from './crown-gold.png';
export { default as Crown2 } from './crown-silver.png';
export { default as Crown3 } from './crown-bronze.png';

const SnooFaceSVG = './snoo-face.svg';
export { SnooFaceSVG };
